const event = {
  couple: "Марат & Карина",
  dateIso: "2026-09-12T11:00:00+03:00",
  dateDisplay: "12 сентября 2026",
  timeDisplay: "11:00",
  basmala: "С именем Аллаха Милостивого, Милосердного",
  invitationText: "С благодарностью Всевышнему мы приглашаем Вас разделить с нами светлый и торжественный день нашего никаха. Ваше присутствие станет для нас искренней радостью и частью теплых воспоминаний.",
  guestText: "Будем счастливы разделить этот особенный день вместе с Вами.",
  venue: {
    name: "Банкетный зал «Nur»",
    address: "г. Казань, ул. Примерная, 12",
    time: "Сбор гостей в 10:40",
    mapUrl: "https://maps.google.com/?q=Kazan",
  },
  program: [
    ["11:00", "Никах"],
    ["13:00", "Праздничный обед"],
    ["15:00", "Завершение"],
  ],
  guests: {
    azat: "Азат",
    ruslan: "Руслан",
    amilya: "Амиля",
    marinarobert: "Марина и Роберт",
  },
};

const css = `
:root{--e0:#041f1b;--e1:#062f29;--e2:#0a4238;--g:#d6b66f;--gs:#f1dfaa;--m:#f7f1e4;--md:#d9cfbd;--line:rgba(214,182,111,.34)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;min-height:100vh;color:var(--m);background:radial-gradient(circle at 50% -12%,rgba(214,182,111,.16),transparent 34rem),linear-gradient(145deg,var(--e0),var(--e1) 42%,#021512);font-family:Manrope,Arial,sans-serif}button,input{font:inherit}.site-shell{position:relative;width:min(100%,760px);margin:0 auto;overflow:hidden}.ambient{position:fixed;inset:0;pointer-events:none;overflow:hidden}.ambient span{position:absolute;width:4px;height:4px;border-radius:50%;background:rgba(241,223,170,.7);box-shadow:0 0 18px rgba(214,182,111,.9);animation:floatGold 8s ease-in-out infinite}.ambient span:nth-child(1){left:18%;top:18%}.ambient span:nth-child(2){left:78%;top:24%;animation-delay:1.6s}.ambient span:nth-child(3){left:66%;top:68%;animation-delay:3.2s}.ambient span:nth-child(4){left:28%;top:76%;animation-delay:4.4s}
.hero{position:relative;min-height:96svh;padding:max(28px,env(safe-area-inset-top)) 22px 34px;display:grid;place-items:center;isolation:isolate}.hero:before{content:"";position:absolute;inset:14px;border:1px solid var(--line);border-radius:34px}.hero:after{content:"";position:absolute;width:116%;height:45%;bottom:-15%;left:-8%;background:radial-gradient(ellipse at center,rgba(214,182,111,.14),transparent 62%);z-index:-1}.ornament{position:absolute;left:50%;width:min(82vw,390px);height:76px;transform:translateX(-50%);opacity:.42;background-image:linear-gradient(45deg,transparent 45%,var(--g) 47%,var(--g) 53%,transparent 55%),linear-gradient(-45deg,transparent 45%,var(--g) 47%,var(--g) 53%,transparent 55%);background-size:24px 24px;mask-image:linear-gradient(90deg,transparent,#000 16%,#000 84%,transparent)}.ornament-top{top:38px}.ornament-bottom{bottom:28px;transform:translateX(-50%) rotate(180deg)}
.hero-arch{position:absolute;width:min(76vw,330px);height:min(72vh,560px);top:50%;left:50%;transform:translate(-50%,-50%);border:1px solid rgba(214,182,111,.55);border-bottom:0;border-radius:50% 50% 18px 18px/26% 26% 18px 18px;box-shadow:inset 0 0 0 8px rgba(214,182,111,.035),0 0 45px rgba(214,182,111,.13);overflow:hidden}.hero-arch:before{content:"";position:absolute;inset:18px;border:1px solid rgba(214,182,111,.24);border-bottom:0;border-radius:inherit}.arch-door{position:absolute;top:0;bottom:0;width:50.5%;background:linear-gradient(90deg,rgba(214,182,111,.16),transparent 16%,transparent 84%,rgba(214,182,111,.1)),repeating-linear-gradient(45deg,rgba(241,223,170,.08) 0 1px,transparent 1px 30px),linear-gradient(180deg,rgba(16,88,74,.98),rgba(4,31,27,.98));transition:transform 1.25s cubic-bezier(.2,.75,.18,1),opacity 1.1s ease}.arch-left{left:0;transform-origin:left center;border-right:1px solid rgba(214,182,111,.44)}.arch-right{right:0;transform-origin:right center;border-left:1px solid rgba(214,182,111,.44)}.arch-line{position:absolute;inset:42px 36px;border:1px solid rgba(241,223,170,.2);border-bottom:0;border-radius:inherit}.opened .arch-left{transform:perspective(900px) rotateY(-74deg);opacity:.52}.opened .arch-right{transform:perspective(900px) rotateY(74deg);opacity:.52}
.hero-content{position:relative;z-index:2;width:100%;max-width:390px;text-align:center;padding:42px 20px}.kicker,.eyebrow{margin:0 0 12px;color:var(--gs);font-size:12px;font-weight:700;letter-spacing:.22em;text-transform:uppercase}h1,h2,.large-date{font-family:"Cormorant Garamond",Georgia,serif;font-weight:600}h1{margin:0;font-size:clamp(54px,17vw,82px);line-height:.88;text-shadow:0 0 26px rgba(214,182,111,.22)}h2{margin:0 0 12px;font-size:36px;line-height:1}.basmala{max-width:280px;margin:26px auto 18px;color:var(--md);font-family:"Cormorant Garamond",Georgia,serif;font-size:23px;line-height:1.18}.date-place{width:fit-content;margin:0 auto 28px;padding:8px 18px;color:var(--gs);border-top:1px solid var(--line);border-bottom:1px solid var(--line);font-size:14px}
.gold-button,.outline-button,.quiet-button,.copy-button{min-height:50px;border-radius:999px;border:1px solid transparent;padding:0 22px;cursor:pointer;transition:transform .25s ease,box-shadow .25s ease,background .25s ease}.gold-button{color:#10221e;background:linear-gradient(135deg,var(--gs),var(--g) 55%,#b58d46);box-shadow:0 12px 34px rgba(0,0,0,.32),0 0 24px rgba(214,182,111,.2);font-weight:700}.outline-button,.quiet-button{display:inline-flex;align-items:center;justify-content:center;color:var(--gs);background:rgba(247,241,228,.04);border-color:var(--line);text-decoration:none}.quiet-button{color:var(--m)}.copy-button{min-height:36px;padding:0 14px;color:var(--e0);background:var(--gs);white-space:nowrap}
.content{max-height:0;opacity:0;transform:translateY(28px);transition:max-height 1.1s ease,opacity .8s ease,transform .8s ease}.opened .content{max-height:5000px;opacity:1;transform:translateY(0)}.section{margin:0 18px 18px;padding:30px 22px;border-top:1px solid var(--line);background:linear-gradient(180deg,rgba(247,241,228,.055),rgba(247,241,228,.022))}.section p{margin:0;color:var(--md);line-height:1.72}.guest-card,.date-section{text-align:center}.large-date{font-size:clamp(48px,15vw,72px);line-height:.94}.large-time{margin-top:10px;color:var(--gs);font-size:18px}.countdown{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.countdown div,.stats-grid div{min-width:0;padding:16px 8px;border:1px solid var(--line);background:rgba(4,31,27,.42);text-align:center}.countdown strong,.stats-grid strong{display:block;color:var(--gs);font-family:"Cormorant Garamond",Georgia,serif;font-size:32px;line-height:1}.countdown span,.stats-grid span{display:block;margin-top:8px;color:var(--md);font-size:11px}.venue-time{margin:10px 0 20px!important;color:var(--gs)!important}
.timeline{position:relative;margin-top:18px;padding-left:26px}.timeline:before{content:"";position:absolute;left:7px;top:8px;bottom:8px;width:1px;background:var(--line)}.timeline-item{position:relative;display:grid;grid-template-columns:70px 1fr;gap:14px;padding:12px 0}.timeline-item:before{content:"";position:absolute;left:-24px;top:19px;width:13px;height:13px;border:1px solid var(--g);border-radius:50%;background:var(--e1);box-shadow:0 0 14px rgba(214,182,111,.35)}.timeline-item time{color:var(--gs);font-weight:700}.rsvp-actions{display:grid;gap:10px;margin-top:18px}.rsvp-result{min-height:28px;margin-top:16px!important;color:var(--gs)!important;text-align:center}
.music-pill{position:fixed;right:16px;bottom:max(16px,env(safe-area-inset-bottom));z-index:20;display:inline-flex;align-items:center;gap:8px;min-height:42px;max-width:calc(100vw - 32px);padding:0 14px;color:var(--gs);background:rgba(4,31,27,.78);border:1px solid rgba(214,182,111,.42);border-radius:999px;box-shadow:0 12px 30px rgba(0,0,0,.26),0 0 18px rgba(214,182,111,.12);backdrop-filter:blur(14px);cursor:pointer}.music-dot{width:8px;height:8px;border-radius:50%;background:var(--g);box-shadow:0 0 14px rgba(214,182,111,.72)}.music-pill.playing .music-dot{animation:musicPulse 1.7s ease-in-out infinite}
.admin-dashboard{width:min(100% - 28px,1040px);margin:0 auto;padding:28px 0}.admin-header{display:flex;align-items:center;justify-content:space-between;gap:16px;margin-bottom:18px}.admin-header h1{margin:0;font-family:"Cormorant Garamond",Georgia,serif;font-size:42px}.stats-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:18px}.admin-create{display:grid;grid-template-columns:1fr 1fr auto;gap:12px;align-items:end;padding:16px;margin-bottom:18px;border:1px solid var(--line);background:rgba(247,241,228,.045)}label{display:grid;gap:8px;color:var(--md);font-size:13px}input{width:100%;min-height:48px;padding:0 16px;color:var(--m);background:rgba(247,241,228,.07);border:1px solid var(--line);border-radius:14px;outline:none}.table-wrap{overflow-x:auto;border:1px solid var(--line);background:rgba(247,241,228,.045)}table{width:100%;border-collapse:collapse;min-width:760px}th,td{padding:14px;border-bottom:1px solid rgba(214,182,111,.18);text-align:left;color:var(--md)}th{color:var(--gs);font-size:12px;text-transform:uppercase;letter-spacing:.08em}.admin-link{color:var(--gs);word-break:break-all}
.reveal{opacity:0;transform:translateY(22px);transition:opacity .7s ease,transform .7s ease}.reveal.visible{opacity:1;transform:translateY(0)}@keyframes floatGold{0%,100%{transform:translate3d(0,0,0);opacity:.28}50%{transform:translate3d(10px,-26px,0);opacity:.82}}@keyframes musicPulse{0%,100%{transform:scale(1);opacity:.78}50%{transform:scale(1.55);opacity:1}}@media(max-width:620px){.countdown{gap:6px}.countdown div{padding:14px 4px}.countdown strong{font-size:28px}.stats-grid{grid-template-columns:repeat(2,1fr)}.admin-header,.admin-create{display:grid;grid-template-columns:1fr}}
`;

function esc(value) {
  return String(value).replace(/[&<>"']/g, (char) => ({
    "&": "&amp;",
    "<": "&lt;",
    ">": "&gt;",
    '"': "&quot;",
    "'": "&#39;",
  })[char]);
}

function titleName(slug) {
  if (!slug) return "";
  if (event.guests[slug]) return event.guests[slug];
  return slug.split("-").filter(Boolean).map((part) => part[0].toUpperCase() + part.slice(1)).join(" ");
}

function page(path) {
  const isAdmin = path.startsWith("/admin");
  const slug = path.startsWith("/invite/") ? decodeURIComponent(path.replace("/invite/", "").replace(/\/$/, "")) : "";
  const guest = titleName(slug);
  return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#062f29"><title>Никах | ${event.couple}</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600;700&family=Manrope:wght@400;500;600;700&display=swap" rel="stylesheet"><style>${css}</style></head><body>${isAdmin ? adminHtml() : inviteHtml(guest, slug)}<script>${clientJs()}</script></body></html>`;
}

function inviteHtml(guest, slug) {
  const greet = guest ? ((guest.toLowerCase().includes(" и ") || guest.toLowerCase().includes("&") || guest.toLowerCase().includes("семья")) ? "Дорогие" : "Дорогой") : "Дорогие";
  return `<main class="site-shell" data-date="${event.dateIso}" data-slug="${esc(slug || "guest")}"><div class="ambient"><span></span><span></span><span></span><span></span></div><section class="hero"><div class="ornament ornament-top"></div><div class="hero-arch"><div class="arch-door arch-left"></div><div class="arch-door arch-right"></div><div class="arch-line"></div></div><div class="hero-content"><p class="kicker">НИКАХ</p><h1>${event.couple}</h1><p class="basmala">${event.basmala}</p><div class="date-place">${event.dateDisplay}</div><button class="gold-button" id="open">Открыть приглашение</button></div><div class="ornament ornament-bottom"></div></section><div class="content"><section class="section guest-card reveal"><p class="eyebrow">Персональное приглашение</p><h2>${guest ? `${greet} ${esc(guest)}!` : "Дорогие гости!"}</h2><p>${event.guestText}</p></section><section class="section reveal"><p class="eyebrow">С любовью и уважением</p><h2>Приглашение на никах</h2><p>${event.invitationText}</p></section><section class="section date-section reveal"><p class="eyebrow">Дата торжества</p><div class="large-date">${event.dateDisplay}</div><div class="large-time">${event.timeDisplay}</div></section><section class="section reveal"><p class="eyebrow">До встречи осталось</p><div class="countdown"><div><strong data-days>00</strong><span>Дни</span></div><div><strong data-hours>00</strong><span>Часы</span></div><div><strong data-minutes>00</strong><span>Минуты</span></div><div><strong data-seconds>00</strong><span>Секунды</span></div></div></section><section class="section venue reveal"><p class="eyebrow">Место проведения</p><h2>${event.venue.name}</h2><p>${event.venue.address}</p><p class="venue-time">${event.venue.time}</p><a class="outline-button" href="${event.venue.mapUrl}" target="_blank" rel="noopener">Открыть на карте</a></section><section class="section reveal"><p class="eyebrow">Программа дня</p><div class="timeline">${event.program.map(([time, title]) => `<div class="timeline-item"><time>${time}</time><span>${title}</span></div>`).join("")}</div></section><section class="section rsvp reveal"><p class="eyebrow">Подтверждение</p><h2>Будете ли вы с нами?</h2><div class="rsvp-actions"><button class="gold-button" data-rsvp="Спасибо, будем ждать Вас!">С радостью приду</button><button class="quiet-button" data-rsvp="Спасибо, что сообщили нам.">К сожалению, не смогу</button></div><p class="rsvp-result" id="rsvpResult">Ответ сохранится на этом устройстве.</p></section></div><button class="music-pill" id="music"><span class="music-dot"></span><span id="musicText">Включить музыку</span></button></main>`;
}

function adminHtml() {
  const rows = Object.entries(event.guests).map(([slug, name]) => `<tr><td>${esc(name)}</td><td><a class="admin-link" href="/invite/${slug}">/invite/${slug}</a></td><td><button class="copy-button" data-copy="/invite/${slug}">Скопировать</button></td></tr>`).join("");
  return `<main class="admin-dashboard"><header class="admin-header"><div><p class="eyebrow">Админ-панель</p><h1>Ссылки гостей</h1></div><a class="outline-button" href="/">Приглашение</a></header><section class="stats-grid"><div><strong>${Object.keys(event.guests).length}</strong><span>Готовых ссылок</span></div><div><strong>0</strong><span>Придут</span></div><div><strong>0</strong><span>Не придут</span></div><div><strong>${Object.keys(event.guests).length}</strong><span>Не ответили</span></div></section><section class="admin-create"><label><span>Имя гостя</span><input id="newName" placeholder="Азат и Алия"></label><label><span>Ссылка</span><input id="newSlug" placeholder="azat-aliya"></label><button class="gold-button" id="copyNew">Скопировать новую</button></section><section class="table-wrap"><table><thead><tr><th>Имя</th><th>Ссылка</th><th></th></tr></thead><tbody id="guestRows">${rows}</tbody></table></section></main>`;
}

function clientJs() {
  return `function slugify(v){return v.trim().toLowerCase().replace(/[^a-zа-яё0-9_-]+/gi,"-").replace(/-{2,}/g,"-").replace(/^-|-$/g,"")}async function copy(v,b){await navigator.clipboard.writeText(location.origin+v);if(b){var t=b.textContent;b.textContent="Скопировано";setTimeout(function(){b.textContent=t},1400)}}document.querySelectorAll("[data-copy]").forEach(function(b){b.onclick=function(){copy(b.dataset.copy,b)}});var copyNew=document.getElementById("copyNew");if(copyNew){copyNew.onclick=function(){var n=document.getElementById("newName").value;var s=slugify(document.getElementById("newSlug").value||n);if(s)copy("/invite/"+s,copyNew)}}var shell=document.querySelector(".site-shell");var open=document.getElementById("open");if(open){open.onclick=function(){shell.classList.add("opened");setTimeout(function(){document.querySelector(".content").scrollIntoView({behavior:"smooth"})},620)}}var d=shell?new Date(shell.dataset.date):null;function pad(v){return String(v).padStart(2,"0")}function tick(){if(!d)return;var diff=Math.max(0,d.getTime()-Date.now());var total=Math.floor(diff/1000);var vals={days:Math.floor(total/86400),hours:Math.floor(total%86400/3600),minutes:Math.floor(total%3600/60),seconds:total%60};["days","hours","minutes","seconds"].forEach(function(k){var e=document.querySelector("[data-"+k+"]");if(e)e.textContent=pad(vals[k])})}tick();setInterval(tick,1000);var obs=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting)e.target.classList.add("visible")})},{threshold:.12});document.querySelectorAll(".reveal").forEach(function(n){obs.observe(n)});document.querySelectorAll("[data-rsvp]").forEach(function(b){b.onclick=function(){localStorage.setItem("nikah-rsvp-"+(shell.dataset.slug||"guest"),b.dataset.rsvp);document.getElementById("rsvpResult").textContent=b.dataset.rsvp}});var saved=shell?localStorage.getItem("nikah-rsvp-"+(shell.dataset.slug||"guest")):"";if(saved&&document.getElementById("rsvpResult"))document.getElementById("rsvpResult").textContent=saved;var music=document.getElementById("music");if(music){music.onclick=function(){music.classList.toggle("playing");document.getElementById("musicText").textContent=music.classList.contains("playing")?"Выключить музыку":"Включить музыку"}}`;
}

export default {
  fetch(request) {
    const url = new URL(request.url);
    return new Response(page(url.pathname), {
      headers: { "content-type": "text/html; charset=utf-8" },
    });
  },
};
